apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: services-activity
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
  selector:
    application: frontend