apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-pageview
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: k8s-pageview
        image: <username>/pageview:v0.0.2